# SafeSecrets Interactive Setup Script
# This script helps you configure the environment for local development

Write-Host "=== SafeSecrets Setup ===" -ForegroundColor Cyan
Write-Host ""

# Check if backend/.env exists
$envPath = "backend\.env"
$envExists = Test-Path $envPath

if ($envExists) {
    Write-Host "Found existing backend/.env file" -ForegroundColor Green
    $overwrite = Read-Host "Do you want to reconfigure? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Setup cancelled. Using existing configuration." -ForegroundColor Yellow
        exit 0
    }
}

Write-Host ""
Write-Host "This application requires:" -ForegroundColor Yellow
Write-Host "  - AWS credentials (for Bedrock LLM and Transcribe STT)"
Write-Host "  - Smallest.ai API key (optional, only for 'Full US + Smallest.ai' mode)"
Write-Host ""

# Check AWS credentials
Write-Host "Checking AWS credentials..." -ForegroundColor Cyan
try {
    $awsCheck = aws sts get-caller-identity 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✓ AWS credentials found and valid" -ForegroundColor Green
        $awsConfigured = $true
    } else {
        Write-Host "✗ AWS credentials not configured or invalid" -ForegroundColor Red
        $awsConfigured = $false
    }
} catch {
    Write-Host "✗ AWS CLI not found or credentials not configured" -ForegroundColor Red
    $awsConfigured = $false
}

if (-not $awsConfigured) {
    Write-Host ""
    Write-Host "AWS credentials are required for AWS-based modes:" -ForegroundColor Yellow
    Write-Host "  - Amazon Bedrock (LLM inference)"
    Write-Host "  - Amazon Transcribe (speech-to-text)"
    Write-Host "  - Amazon Polly (text-to-speech)"
    Write-Host ""
    Write-Host "However, you can use the 'AWS-Free' mode with just:" -ForegroundColor Green
    Write-Host "  - OpenAI API key (for LLM)"
    Write-Host "  - Smallest.ai API key (for STT + TTS)"
    Write-Host ""
    Write-Host "Configure AWS credentials later if you want AWS-based modes:" -ForegroundColor Yellow
    Write-Host "  1. Install AWS CLI: https://aws.amazon.com/cli/"
    Write-Host "  2. Run: aws configure"
    Write-Host "  3. Or set environment variables: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY"
    Write-Host ""
}

Write-Host ""
Write-Host "=== API Keys Configuration ===" -ForegroundColor Cyan
Write-Host ""

# Smallest.ai API Key
Write-Host "--- Smallest.ai API Key ---" -ForegroundColor Yellow
Write-Host "Required for:" -ForegroundColor Gray
Write-Host "  - 'Full US + Smallest.ai' mode (TTS only)" -ForegroundColor Gray
Write-Host "  - 'AWS-Free' mode (STT + TTS)" -ForegroundColor Gray
Write-Host "Get your key from: https://smallest.ai" -ForegroundColor Gray
Write-Host ""

$smallestKey = Read-Host "Enter your Smallest.ai API key (or press Enter to skip)"

if ([string]::IsNullOrWhiteSpace($smallestKey)) {
    Write-Host "Skipping Smallest.ai. You can add it later to backend/.env" -ForegroundColor Yellow
    $smallestKey = "your_smallest_ai_api_key_here"
}

Write-Host ""

# OpenAI API Key
Write-Host "--- OpenAI API Key ---" -ForegroundColor Yellow
Write-Host "Required for:" -ForegroundColor Gray
Write-Host "  - 'AWS-Free' mode (LLM inference)" -ForegroundColor Gray
Write-Host "Get your key from: https://platform.openai.com/api-keys" -ForegroundColor Gray
Write-Host ""

$openaiKey = Read-Host "Enter your OpenAI API key (or press Enter to skip)"

if ([string]::IsNullOrWhiteSpace($openaiKey)) {
    Write-Host "Skipping OpenAI. You can add it later to backend/.env" -ForegroundColor Yellow
    $openaiKey = "your_openai_api_key_here"
}

# Create .env file
Write-Host ""
Write-Host "Creating backend/.env file..." -ForegroundColor Cyan

$envContent = @"
# SafeSecrets Backend - Local Development
# Generated by setup.ps1

# Server configuration
PORT=8080
AWS_REGION=ca-central-1
NODE_ENV=development

# Smallest.ai API Key (for STT + TTS in AWS-free mode, or TTS only in other modes)
# Get your key from https://smallest.ai
SMALLEST_AI_API_KEY=$smallestKey

# OpenAI API Key (for LLM in AWS-free mode)
# Get your key from https://platform.openai.com/api-keys
OPENAI_API_KEY=$openaiKey

# Optional: Override models
# BEDROCK_MODEL_ID=anthropic.claude-3-haiku-20240307-v1:0
# OPENAI_MODEL_ID=gpt-4o-mini

# AWS Credentials (not needed for AWS-free mode):
# The AWS SDK automatically loads credentials from:
# 1. Environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)
# 2. AWS credentials file (~/.aws/credentials)
# 3. IAM role (when running on EC2)
"@

$envContent | Out-File -FilePath $envPath -Encoding UTF8

Write-Host "✓ Created $envPath" -ForegroundColor Green
Write-Host ""

# Install dependencies
Write-Host "=== Installing Dependencies ===" -ForegroundColor Cyan
Write-Host "Installing backend dependencies..." -ForegroundColor Gray
Push-Location backend
npm install
Pop-Location

Write-Host "Installing frontend dependencies..." -ForegroundColor Gray
Push-Location frontend
npm install
Pop-Location

Write-Host "Installing shared dependencies..." -ForegroundColor Gray
Push-Location shared
npm install
npm run build
Pop-Location

Write-Host ""
Write-Host "=== Setup Complete! ===" -ForegroundColor Green
Write-Host ""
Write-Host "To start the application:" -ForegroundColor Cyan
Write-Host "  1. Backend:  cd backend && npm run dev" -ForegroundColor White
Write-Host "  2. Frontend: cd frontend && npm run dev" -ForegroundColor White
Write-Host ""
Write-Host "Then open http://localhost:5173 in your browser" -ForegroundColor Cyan
Write-Host ""

if (-not $awsConfigured) {
    Write-Host "⚠ Remember to configure AWS credentials before starting!" -ForegroundColor Yellow
    Write-Host ""
}
